-- Configuration only. Travel sample content is managed through the CMS API, not Flyway.
CREATE TABLE app.cms_code_group (
    group_key VARCHAR(40) PRIMARY KEY,
    label VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0 CHECK (display_order >= 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE app.cms_code (
    code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_key VARCHAR(40) NOT NULL REFERENCES app.cms_code_group(group_key),
    code_value VARCHAR(40) NOT NULL,
    label VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0 CHECK (display_order >= 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_cms_code_group_value UNIQUE (group_key, code_value)
);

ALTER TABLE app.cms_board
    ADD COLUMN display_type VARCHAR(8) NOT NULL DEFAULT 'LIST' CHECK (display_type IN ('LIST', 'CARD')),
    ADD COLUMN region_group_key VARCHAR(40) REFERENCES app.cms_code_group(group_key),
    ADD COLUMN category_group_key VARCHAR(40) REFERENCES app.cms_code_group(group_key);

ALTER TABLE app.cms_post
    ADD COLUMN thumbnail_image_id BIGINT REFERENCES app.cms_content_image(image_id),
    ADD COLUMN thumbnail_alt VARCHAR(200) NOT NULL DEFAULT '',
    ADD COLUMN region_code_id BIGINT REFERENCES app.cms_code(code_id),
    ADD COLUMN category_code_id BIGINT REFERENCES app.cms_code(code_id);

GRANT SELECT, INSERT, UPDATE ON app.cms_code_group, app.cms_code TO cms_app;
GRANT USAGE, SELECT ON SEQUENCE app.cms_code_code_id_seq TO cms_app;
GRANT SELECT ON app.cms_code_group, app.cms_code TO dbeaver_reader;
